config/routes.rb
ForgetPassword::Application.routes.draw do
  get "i_mtl/submitRequest"
  
  root 'static_pages#home'
  match '/feedback', to: 'static_pages#feedback', via:'get'
  match '/faq', to: 'static_pages#faq', via: 'get'
  match '/submitrequest', to: 'i_mtl#submitRequest', via: 'get'
  

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def home
  
  end
  
  def faq
  
  end
  
  def feedback
  
  end

end

app/controllers/i_mtl_controller.rb
class IMtlController < ApplicationController
  def submitRequest
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def faq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/i_mtl_helper.rb
module IMtlHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/i_mtl/submitRequest.html.erb
<%provide(:title, 'iMTL Password Reset')%>

<h1> iMTL Password Reset </h1>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        <center>
            <a href="http:www.commonwealthsec.moe.edu.sg"> Commonwealth Secondary School </a>
            <h6> 698 West Coast Road Singapore 608784 </h6>
        </center>
    </small>
</footer>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <%= link_to "CWSS 4get Ur Password", '#', id:"logo"%>
                <nav>
                    <ul class = "nav pull-right">
                        <li><%= link_to "Home", root_path%></li>
                        <li><%= link_to "FAQ", faq_path%></li>
                        <li><%= link_to "Feedback", feedback_path%></li>
                    </ul>
                </nav>
            </div>
        </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>
            Commonwealth Secondary School | <%= yield(:title)%>
        </title>
        
        <%= stylesheet_link_tag "application", media: "all", "data-tubolinks-track"=> true %>

        <%= csrf_meta_tags%>
        <%= render 'layouts/shim'%>
    </head>

    <body>
    <%=render 'layouts/header' %>
        
        <div class="container">
            <%= yield %>
      <%= render 'layouts/footer'%>
        </div>
    </body>
</html>

app/views/static_pages/faq.html.erb
<%provide(:title, 'FAQ')%>

<h1> FAQ </h1>
<p> 
    Below are some of the very common questions students will ask about password change.
</p>

app/views/static_pages/feedback.html.erb
<%provide(:title, 'Feedback')%>

<h1>Feedback </h1>

<p> 
    This web is just a start point. We hope to serve you better. If you have any feedbacks on how to improve this web, please feel free to contact us or fill up the form below.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">

    <%provide(:title, 'Home')%>

    <h1>
        Welcome to CWSS 4get Ur Password Portal
    </h1>
        
    <p>
        In this portal, you can send a request to change your password. Click on any of the below to get started.
    </p>

    <%= link_to "Reset iMTL Password", submitrequest_path, class: "btn btn-large btn-primary"%>
    <%= link_to "Reset Windows Login Password", '#', class: "btn btn-large btn-primary"%>
    <%= link_to "Reset Google Password", '#', class: "btn btn-large btn-primary"%>
    <%= link_to "Reset Ask 'N' Learn Password", '#', class: "btn btn-large btn-primary"%>
</div>